# name: Daily Commit

# on:
#   schedule:
#     - cron: "0 0 * * *"   # runs daily at midnight UTC
#   workflow_dispatch:      # allows manual run

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v3

#       - name: Run Script
#         run: |
#           bash update.sh
# # 
name: Daily Commit

on:
  schedule:
    - cron: "30 18 * * *"   # runs daily at 00:00 IST
  workflow_dispatch:        # allows manual run

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "Last run: $(date)" >> log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add log.txt
          git commit -m "Automated commit: $(date)"
          git push
